# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=2500)),
                ('email', models.CharField(max_length=2500)),
                ('alternate_no', models.CharField(max_length=250)),
                ('date_join', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('type1', models.CharField(max_length=250)),
                ('dep', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_id', models.CharField(max_length=250)),
                ('em_name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('leave_from', models.CharField(max_length=250)),
                ('leave_to', models.CharField(max_length=250)),
                ('no_days', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('mounth', models.CharField(max_length=250)),
                ('leaves_no_days', models.CharField(max_length=250)),
                ('actual_ctc', models.CharField(max_length=250)),
                ('payble_ctc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=250)),
                ('em_father_mother_name', models.CharField(max_length=250)),
                ('em_dob', models.CharField(max_length=250)),
                ('em_address', models.CharField(max_length=250)),
                ('em_aadher_number', models.CharField(max_length=150)),
                ('em_mobile', models.CharField(max_length=250)),
                ('em_email', models.CharField(max_length=250)),
                ('em_alternate_no', models.CharField(max_length=250)),
                ('em_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
